Snyk

diff --git a/.github/workflows/snyk-container.yml b/.github/workflows/snyk-container.yml
--- a/.github/workflows/snyk-container.yml
+++ b/.github/workflows/snyk-container.yml
@@ -32,6 +32,13 @@ jobs:
             --file=Dockerfile
             --sarif-file-output=/github/workspace/snyk.sarif
       
+      - name: Check if SARIF file exists
+        run: |
+          if [ ! -f /github/workspace/snyk.sarif ]; then
+            echo "SARIF file not found"
+            exit 1
+          fi
+      
       - name: Validate SARIF file
         run: |
           if ! jq -e '.runs[].results[].ruleId' /github/workspace/snyk.sarif > /dev/null; then
