prueba

diff --git a/.github/workflows/snyk-container.yml b/.github/workflows/snyk-container.yml
--- a/.github/workflows/snyk-container.yml
+++ b/.github/workflows/snyk-container.yml
@@ -6,7 +6,7 @@ on:
   pull_request:
     branches: [ "main" ]
   schedule:
-    - cron: '18 0 * * 2'
+    - cron: '18 9 * * 3'
 
 permissions:
   contents: read
@@ -14,30 +14,35 @@ permissions:
 jobs:
   snyk:
     permissions:
-      contents: read # para que actions/checkout pueda obtener el código
-      security-events: write # para que github/codeql-action/upload-sarif pueda subir los resultados SARIF
-      actions: read # solo necesario para un repositorio privado y obtener el estado de la ejecución
+      contents: read
+      security-events: write
+      actions: read
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - name: Build a Docker image
-      run: docker build -t your/image-to-test .
+      - uses: actions/checkout@v3
       
-    - name: Run Snyk to check Docker image for vulnerabilities
-      continue-on-error: true
-      uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
-      env:
-        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-      with:
-        image: your/image-to-test
-        args: --file=Dockerfile --sarif
-
-    # Nuevo paso para corregir posibles valores nulos en el archivo SARIF
-    - name: Sanitize SARIF file
-      run: |
-        sed -i 's/"security-severity": null/"security-severity": 0/g' snyk.sarif
-
-    - name: Upload result to GitHub Code Scanning
-      uses: github/codeql-action/upload-sarif@v3
-      with:
-        sarif_file: snyk.sarif
+      - name: Build a Docker image
+        run: docker build -t your/image-to-test .
+      
+      - name: Run Snyk to check Docker image for vulnerabilities
+        continue-on-error: true
+        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          image: your/image-to-test
+          args: |
+            --file=Dockerfile
+            --sarif-file-output=snyk.sarif
+      
+      - name: Debug SARIF file creation
+        if: always()
+        run: |
+          echo "Checking current directory for SARIF file:"
+          ls -la
+          find / -name "*.sarif" 2>/dev/null || echo "SARIF file not found"
+      
+      - name: Upload result to GitHub Code Scanning
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
